### İmport

In [1]:
import numpy as np

### Numpy Arrays

In [2]:
liste =[10,20,30,40,50,60,70,80,90,100]
print(type(liste))
print(type(np.array(liste)))


<class 'list'>
<class 'numpy.ndarray'>


In [31]:
array = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
np.array(array)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Arange

In [37]:
array=np.arange(0,10,0.5)
array

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

### Zeros and Ones

In [43]:
a=np.zeros(5)
b=np.zeros((5,5))
c=np.ones(5)
print(a , b , c)

[0. 0. 0. 0. 0.] [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] [1. 1. 1. 1. 1.]


### Linspace
* eşit aralıklarda istediğimiz kadar eleman oluşturmaya yarar

In [48]:
np.linspace(0,20,19) # 0 ile 20 arasında 19 eleman

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ,
       11.11111111, 12.22222222, 13.33333333, 14.44444444, 15.55555556,
       16.66666667, 17.77777778, 18.88888889, 20.        ])

### Eye
* Daha Çok Birim Matris OLuşturmak için Kullanılır

In [54]:
np.eye(3,4)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random

In [74]:
np.random.rand(5)
np.random.rand(5,5)
np.random.randint(0,10,10)

array([8, 0, 5, 9, 6, 0, 9, 8, 1, 0])