In [1]:
import numpy as np

### Dizi Methotları

In [19]:
dizi=np.random.randint(0,10,10)
dizi

array([3, 1, 9, 9, 8, 6, 8, 3, 0, 8])

In [28]:
print(dizi.reshape(5,2))
dizi.shape

[[3 1]
 [9 9]
 [8 6]
 [8 3]
 [0 8]]


(5, 2)

In [30]:
dizi.max()
dizi.min()
dizi.sum()
dizi.mean()
dizi.std()
dizi.var()
dizi.argmax() # max elemanın indexi 
dizi.argmin() 
dizi.argmax(axis=0) # max elemanın indexleri
dizi.argmin(axis=0) 

array([4, 0])

### Numpy İndexler

In [53]:
dizi = np.arange(0,10)
dizi[5]
dizi[0:3:5]
dizi[0::5]
dizi[0:5] = -15
dizi


array([-15, -15, -15, -15, -15,   5,   6,   7,   8,   9])

### Matrix

In [60]:
örk=[[10,20,30],[40,50,60],[70,80,90]]
örk=np.array(örk)
örk

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [65]:
örk[0,0]
örk[0:,1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

### Operasyonlar

In [75]:
dizi1=np.arange(0,15)
dizi2=np.arange(0,15)
dizi1+dizi2
dizi>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])